### ISSUE TITLE
max fee per gas less than block base fee: address 

### ISSUE THREAD

**Issue by sokiaoba** [oasysgames/oasys-validator#40]
#### System information

Geth version: `1.2.0`
OS & Version: Linux 

#### Expected behaviour

The following command succeeds with mainnet archive nodes.

```
% curl -X "POST" "https://[MainnetEndpointURL]" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "id": "1",
  "params": ["0x1DCC3E", {"tracer": "callTracer"}]
}'
```

#### Actual behaviour

The command fails with the following error.

```
% curl -X "POST" "https://[MainnetEndpointURL]" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "id": "1",
  "params": ["0x1DCC3E", {"tracer": "callTracer"}]
}'
{"jsonrpc":"2.0","id":"1","error":{"code":-32000,"message":"max fee per gas less than block base fee: address 0x9326839c5372E68e048732c3CD08bb0D2eFe1BB4, maxFeePerGas: 0 baseFee: 7"}}
```

#### Steps to reproduce the behaviour

Run the following command (got the same error from all nodes we're running. but not sure the same error occurs for other nodes)

```
% curl -X "POST" "https://[MainnetEndpointURL]" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "id": "1",
  "params": ["0x1DCC3E", {"tracer": "callTracer"}]
}'
```

#### Backtrace

````
[backtrace]
````

**Comment by tak1827** [comment]
It appears that the system transactions of Oasys PoS contained within that block are the likely cause.
https://explorer.oasys.games/tx/0x105228cab36ecc39004cc9ffae74c8fc4a62f5cbbdb5ab29d295695180b5097e

System transactions follow a different verification process compared to regular transactions, as they are special transactions issued by validators.

This error occurred because the fees for those system transactions were lower than the minimum fees required for the block.
https://github.com/oasysgames/oasys-validator/blob/v1.2.0/core/state_transition.go#L253-L256

Fortunately, the negative impact is truly limited and has no effect on the daily operations of the validator. We will address this issue as soon as we are able to do so.

**Comment by sokiaoba** [comment]
@tak1827 Got it. Thank you for your investigation.
